### ISSUE TITLE
Try using multiprocessing for `save_featurized_data` in datamodule

### ISSUE THREAD

**Issue by callumm-graphcore** [datamol-io/graphium#317]
Currently, this is taking my machine about 15-20 minutes to do. I think using multiprocessing might speed this up significantly

**Comment by DomInvivo** [comment]
I tried naively, but it was much much slower. It depends whether the bottleneck is the disk or the CPU. If it's the disk, then we can't improve on that.

**Comment by zhiyil-graphcore** [comment]
Yeah I also tried to use Pool and multiprocessing initially when working on this, it seems to be much slower than serial processing. I didn't figure out why.

**Comment by DomInvivo** [comment]
Currently, on our server, saving the millions of compounds from the LargeMix dataset takes about 6h and reloading them about 1h30.

An obvious way to speed that up is to use parallelization. However, when implementing datamol.parallelized, the time becomes intractable, with more than 200h for both the loading and the saving.

I am confident that there are some parallel protocols better suited for mass parallelization of pickle files. Let's find and implement them.

**Comment by DomInvivo** [comment]
In PR #450 , we investigated different methods of loading and saving in parallel. 

There has been some success with **loading** using "fork" or "spawn", but the advantages only come with > 100,000k pickle files. This is expected as the dataloading also benefits from these multiprocessing contexts.

However, there's no sign that multiprocessing can help **saving**, with the single thread showing significant speed-up even with 32k files, and we couldn't multiprocess more files due to memory issues and number of files opened errors raised by the operating system.

**Comment by DomInvivo** [comment]
Did some profiling in #450 . Will close this issue for stalling. Not sure if this can be solved, unless we go with C++ directly, or save many molecules per file.
