### ISSUE TITLE
Suggestions on dependencies

### ISSUE THREAD

**Issue by KiddoZhu** [datamol-io/graphium#383]
Conda speed problem
- The current solution is to use mamba.
- The reason is that resolving dependencies in `conda-forge` is usually way slower than in the default channel. Specifying the versions of dependencies may narrow down the search range.
- I suggest using both `anaconda` and `conda-forge`. Conda will greedily find the packages in the first channel, then in the second channel. We can put `conda-forge` behind all the other channels.

Dependencies
- `matplotlib` can be replaced by `matplotlib-base` unless we need to use PyQt.
- `pytorch_geometric`, `pytorch_sparse`, `pytorch_cluster`, `pytorch_scatter` can be installed from `pyg` channel faster due to less dependency search.
- `rdkit` has a channel `rdkit` which is faster for dependency search, but its version is older than the one in `conda-forge`. May still use the `conda-forge`.

I didn't find any dependency that can be obviously removed 😅 .

**Comment by hadim** [comment]
Thank you for your suggestions on the dependencies. This is a topic we are very careful with as it's an important one to ensure our packages can be installed and run without any issues in different computational environments.

---

At datamol.io we only support and also **strongly recommend** using the `conda-forge` channel **only** and no other Anaconda channels (such as `pytorch`, `pyg`, `rdkit` and `anaconda`).

The reason for that is because other channels are not necessary binary compatible with the ones on `conda-forge`. We had many trouble for years internally using a mix of different channels and almost all our issues disappeared when we started relying only on the unique `conda-forge` channel (+ an internal private one containing a few private packages).

Here is an example of binary incompatibility related to `pytorch_geometric`: https://github.com/pyg-team/pytorch_geometric/issues/3660

When a package is not available on `conda-forge` then the best thing to do is to create it on `conda-forge`. Since `conda-forge` is mostly fully automated, any new required rebuild will be taken care of without having to rely on the upstream developers of a specific package. For example, whenever a new CUDA version is out, `conda-forge` will automatically trigger a rebuild of all packages depending on CUDA. Another example is `rdkit` being rebuilt for any new version of `boost` or `python`.

Relying only on `conda-forge` also gives some guarantees in terms of transparency and reproducibility since all the builds are automated on CI and can be inspected. It does not guarantee 0 security risk but so far, it seems to be the best system publicly available out there (versus relying on other channels maintained by smaller teams).

---

On speed, it's true that `conda` used to be very slow (it's easy to find a lot of GH issues related to that topic). Using `mamba` mostly fixes the dep solving speed issue.

I would also recommend you to give it a try to [`micromamba`](https://mamba.readthedocs.io/en/latest/installation.html#micromamba) which is a standalone statically linked binary that ships all the conda/mamba features. It's very snappy. Trying it is adopting it :-)

Also note that the `conda` team has been working very hard the last months to be replaced the Python-based dep solver by the `mamba` one. I haven't tried it myself, but I know it will soon become the new default dep solver in `conda`. You can find more information at https://conda.github.io/conda-libmamba-solver/ and https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community.

---

> matplotlib can be replaced by matplotlib-base unless we need to use PyQt.

This is already the case in the graphium feedstock at https://github.com/conda-forge/graphium-feedstock/blob/de4232fa9f5008cb9c6b499b13b6ea0c884d8d5a/recipe/meta.yaml#L36

---

If you find that `graphium` is slow to install on your system, we would be happy to assist you. Please give us the env.yml file or CLI you are using as well as some information about your system.

**Comment by DomInvivo** [comment]
@KiddoZhu , I think that @hadim answered your question so I will close the issue. Feel free to re-open it if you think it hasn't been answered.
