### ISSUE TITLE
Mixed-precision overflow on GPU

### ISSUE THREAD

**Issue by luis-mueller** [datamol-io/graphium#406]
When using `trainer.trainer.precision: 16` or `16-mixed`, some task metrics are `NaN` or `0` in the validation/test split. Upon further debugging I saw that there all the available graphs in the split are being used at once for the computation of the final metric. Then, a fp16 overflow appears to happen that sets the result to `NaN`. Setting `trainer.trainer.precision: 32` solves the issue.

A potential fix could be to cast to fp32 during loss computation but actually this issue should be fixed with the `GradScaler`. Further investigation is needed.

Tasks where this happens are QM9 on ToyMix and both PCQM4M tasks on LargeMix.

**Comment by DomInvivo** [comment]
@luis-mueller does this happen only for the metrics, or for the loss as well?

**Comment by luis-mueller** [comment]
Only in the metrics.

**Comment by DomInvivo** [comment]
And do you remember if this happens at train time, or only at validation time?

**Comment by luis-mueller** [comment]
It happens during training but only for the validation split and then later also in the test split (after training has finished)

**Comment by luis-mueller** [comment]
One potential solution we discussed in a recent meeting was to simply cast the mae loss to fp32. What’s your opinion on this?

**Comment by DomInvivo** [comment]
Since this happens only at validation and test time, can we cast all preds and targets to fp32 for the metrics computation? In this method? 

https://github.com/datamol-io/graphium/blob/d7c910e43d3576431dea6247ea6fd66dbfd44359/graphium/trainer/predictor_summaries.py#L228C1-L228C1


I don't understand why you talk about the mae loss, when you say the loss has no issue, the issue is with the metrics.

**Comment by luis-mueller** [comment]
You are right, sorry. It definitely happens in the mae loss, not the metrics. Let me get back to you about this with more information.
